blank_issues_enabled: true
contact_links:
  - name: Github support
    url: https://support.github.com/contact?subject=Code+Scanning+Beta+Support&tags=code-scanning-support
    about: Code Scanning Beta Support - Get help with GitHub