# Warning: This file is generated automatically, and should not be modified.
# Instead, please modify the template in the pr-checks directory and run:
#     (cd pr-checks; pip install ruamel.yaml@0.17.31 && python3 sync.py)
# to regenerate this file.

name: 'PR Check - Packaging: Download using registries'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GO111MODULE: auto
on:
  push:
    branches:
    - main
    - releases/v*
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review
  workflow_dispatch: {}
jobs:
  init-with-registries:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          version: default
        - os: macos-latest
          version: default
        - os: windows-latest
          version: default
        - os: ubuntu-latest
          version: latest
        - os: macos-latest
          version: latest
        - os: windows-latest
          version: latest
        - os: ubuntu-latest
          version: nightly-latest
        - os: macos-latest
          version: nightly-latest
        - os: windows-latest
          version: nightly-latest
    name: 'Packaging: Download using registries'
    permissions:
      contents: read
      packages: read

    timeout-minutes: 45
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup Python on MacOS
      uses: actions/setup-python@v5
      if: >-
        matrix.os == 'macos-latest' && (

        matrix.version == 'stable-20221211' ||

        matrix.version == 'stable-20230418' ||

        matrix.version == 'stable-v2.13.5' ||

        matrix.version == 'stable-v2.14.6')
      with:
        python-version: '3.11'
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Prepare test
      id: prepare-test
      uses: ./.github/actions/prepare-test
      with:
        version: ${{ matrix.version }}
        use-all-platform-bundle: 'false'
        setup-kotlin: true
    - name: Set environment variable for Swift enablement
      if: runner.os != 'Windows' && matrix.version == '20221211'
      shell: bash
      run: echo "CODEQL_ENABLE_EXPERIMENTAL_FEATURES_SWIFT=true" >> $GITHUB_ENV
    - name: Init with registries
      uses: ./../action/init
      with:
        db-location: ${{ runner.temp }}/customDbLocation
        tools: ${{ steps.prepare-test.outputs.tools-url }}
        config-file: ./.github/codeql/codeql-config-registries.yml
        languages: javascript
        registries: |
          - url: "https://ghcr.io/v2/"
            packages: "*/*"
            token: "${{ secrets.GITHUB_TOKEN }}"

    - name: Verify packages installed
      shell: bash
      run: |
        PRIVATE_PACK="$HOME/.codeql/packages/codeql-testing/private-pack"
        CODEQL_PACK1="$HOME/.codeql/packages/codeql-testing/codeql-pack1"

        if [[ -d $PRIVATE_PACK ]]
        then
            echo "$PRIVATE_PACK was installed."
        else
            echo "::error $PRIVATE_PACK pack was not installed."
            exit 1
        fi

        if [[ -d $CODEQL_PACK1 ]]
        then
            echo "$CODEQL_PACK1 was installed."
        else
            echo "::error $CODEQL_PACK1 pack was not installed."
            exit 1
        fi

    - name: Verify qlconfig.yml file was created
      shell: bash
      run: |
        QLCONFIG_PATH=$RUNNER_TEMP/qlconfig.yml
        echo "Expected qlconfig.yml file to be created at $QLCONFIG_PATH"
        if [[ -f $QLCONFIG_PATH ]]
        then
            echo "qlconfig.yml file was created."
        else
            echo "::error qlconfig.yml file was not created."
            exit 1
        fi

    - name: Verify contents of qlconfig.yml
    # yq is not available on windows
      if: runner.os != 'Windows'
      shell: bash
      run: |
        QLCONFIG_PATH=$RUNNER_TEMP/qlconfig.yml
        cat $QLCONFIG_PATH | yq -e '.registries[] | select(.url == "https://ghcr.io/v2/") | select(.packages == "*/*")'
        if [[ $? -eq 0 ]]
        then
            echo "Registry was added to qlconfig.yml file."
        else
            echo "::error Registry was not added to qlconfig.yml file."
            echo "Contents of qlconfig.yml file:"
            cat $QLCONFIG_PATH
            exit 1
        fi
    env:
      CODEQL_ACTION_TEST_MODE: true
